AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: One-click Serverless Deploy (Free Tier)

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      CodeUri: src/
      Handler: app.handler
      Timeout: 10
      MemorySize: 128
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: GET

Outputs:
  ApiUrl:
    Description: API endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
